swagger: '2.0'
info:
  title: Rude MCP Server
  description: |
    MCP Server providing Math Tools and Azure Data Explorer integration
    Compatible with Copilot Studio via Streamable HTTP transport (recommended)
  version: 1.0.0
  contact:
    name: Rude MCP Server
    url: https://github.com/your-org/rude-mcp-server
host: rude-mcp.azurewebsites.us
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp/:
    post:
      summary: Rude MCP Server - Math and Azure Data Tools
      description: |
        MCP Server providing mathematical calculations and Azure Data Explorer query capabilities.
        Uses Streamable HTTP transport (recommended by Copilot Studio).
        
        Available Tools:
        - Math operations (add, subtract, multiply, divide, power, square_root, factorial, gcd)
        - Azure Data Explorer queries (list_databases, get_table_schema, execute_query, get_cluster_info, list_tables)
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            description: MCP protocol message
            properties:
              jsonrpc:
                type: string
                enum: ["2.0"]
                description: JSON-RPC version
              id:
                oneOf:
                  - type: string
                  - type: number
                  - type: "null"
                description: Request identifier (can be string, number, or null)
              method:
                type: string
                description: MCP method name
              params:
                type: object
                description: Method parameters
            required:
              - jsonrpc
              - method
      responses:
        '200':
          description: Successful MCP response
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                enum: ["2.0"]
              id:
                oneOf:
                  - type: string
                  - type: number
                  - type: "null"
                description: Response identifier matching request
              result:
                type: object
                description: Method result
              error:
                type: object
                description: Error object if method failed
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /health:
    get:
      summary: Health Check
      description: Simple health check endpoint to verify server is running
      operationId: HealthCheck
      responses:
        '200':
          description: Server is healthy
          schema:
            type: object
            properties:
              status:
                type: string
                enum: ["healthy"]
              timestamp:
                type: string
                format: date-time
              version:
                type: string
              mcp_endpoint:
                type: string
                description: URL for MCP streamable endpoint
definitions:
  MCPError:
    type: object
    properties:
      code:
        type: integer
        description: Error code
      message:
        type: string
        description: Error message
      data:
        type: object
        description: Additional error data
  MCPRequest:
    type: object
    properties:
      jsonrpc:
        type: string
        enum: ["2.0"]
      id:
        oneOf:
          - type: string
          - type: number
          - type: "null"
      method:
        type: string
      params:
        type: object
    required:
      - jsonrpc
      - method
  MCPResponse:
    type: object
    properties:
      jsonrpc:
        type: string
        enum: ["2.0"]
      id:
        oneOf:
          - type: string
          - type: number
          - type: "null"
      result:
        type: object
      error:
        $ref: '#/definitions/MCPError'
    required:
      - jsonrpc
securityDefinitions:
  basic:
    type: basic
    description: Basic authentication if required
  apikey:
    type: apiKey
    in: header
    name: X-API-Key
    description: API key authentication if required
tags:
  - name: MCP
    description: Model Context Protocol endpoints
  - name: Health
    description: Health check endpoints
externalDocs:
  description: Model Context Protocol Specification
  url: https://spec.modelcontextprotocol.io/
